workspace: /apps/workspace

app:
  name: "Yu Gong App"
  port: 3000

cache:
  type: redis
  host: redis.io
  port: 6379
  password: redis123

database:
  dialect: postgres
  host: pgsql.io
  port: 5432
  name: yugong_development
  username: postgres
  password: postgres

proxy:
  host: https://share.proxy.qg.net/pool
  username: EF40DC7E
  password: 8CEF0614705B
